---
- name: Installing Emacs
  package:
    name: emacs-gcc-wayland-devel-bin
    state: present
  become: true
  tags:
    - arch

- name: Installing Emacs
  package:
    name: emacs
    state: present
  become: true
  tags:
    - ubuntu

- name: Summoning Emacs config
  shell: 'bash /home/{{ user_name }}/.local/bin/summon.sh /home/{{ user_name }}/git/github/vinikira/dot-files/common/emacs'

- name: Active Emacs daemon on Systemd (user)
  systemd:
    name: emacs
    state: started
    enabled: yes
    scope: user

- name: Copy emacsclient.desktop
  copy:
    src: '../files/emacsclient.desktop'
    dest: '/home/{{ user_name }}/.local/share/applications/'
