---
- name: Installing Emacs
  package:
    name: emacs
    state: present
  become: true

- name: Summoning Emacs config
  shell: 'sh /home/{{ user_name }}/git/summon/summon.sh /home/{{ user_name }}/git/dot-files/common/emacs'

- name: Active Emacs daemon on Systemd (user)
  systemd:
    name: emacs
    state: started
    enabled: yes
    scope: user

- name: Copy emacsclient.desktop
  copy:
    src: '../files/emacsclient.desktop'
    dest: '/home/{{ user_name }}/.local/share/applications/'
