#!/bin/sh

# Session
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=sway
export XDG_CURRENT_DESKTOP=sway
export GTK_THEME=Adwaita:dark

source /usr/local/bin/wayland_enablement

systemd-cat --identifier=sway sway $@
