#!/usr/bin/env bash

sudo pacman -Syy yay git ansible --noconfirm

mkdir ~/git

git clone http://github.com/vinikira/manjaro-playbook ~/git/github/vinikira/manjaro-playbook/

cd ~/git/github/vinikira/manjaro-playbook/

read -p "Type the user name: " user_name

ansible-playbook playbook.yml --extra-vars="user_name=${user_name}" --ask-become-pass
