#!/usr/bin/env bash

which pacman 2>/dev/null || sudo pacman -Syy yay git ansible --noconfirm

which apt 2>/dev/null || sudo apt install git ansible -y

mkdir ~/git/github

git clone git@github.com:vinikira/linux-playbook.git ~/git/github/vinikira/linux-playbook/

cd ~/git/github/vinikira/linux-playbook/ || exit

read -r -p "Type the user name: " user_name
read -r -p "Type the system tag (ubuntu arch): " system_tag

ansible-playbook playbook.yml --extra-vars="user_name=${user_name}" --ask-become-pass --tags "$system_tag"
