---
- name: Check if Librewolf is installed
  stat:
    path: /usr/bin/librewolf
  register: librewolf
  changed_when: not librewolf.stat.exists

- name: Librewolf Arch
  when: librewolf.changed and ansible_facts['os_family'] == 'Archlinux'
  block:
  - name: Install Librewolf browser
    package:
      name:
        - librewolf-bin
        - browserpass
      state: present
    become: true
  - name: Browser Pass
    make:
      chdir: /usr/lib/browserpass
      target: hosts-librewolf-user

- name: Librewolf Ubuntu
  when: librewolf.changed and ansible_facts['os_family'] == 'Ubuntu'
  block:
  - name: Add PPA Librewolf browser
    become: true
    shell: >
      echo "deb [arch=amd64] http://deb.librewolf.net $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/librewolf.list
      sudo wget https://deb.librewolf.net/keyring.gpg -O /etc/apt/trusted.gpg.d/librewolf.gpg
      sudo apt update

  - name: Install Librewolf
    package:
      name: librewolf
      state: present
    become: true

- name: Browserpass
  block:
  - name: Check if Browserpass is installed
    stat:
      path: /usr/lib/browserpass
    register: browserpass
    changed_when: not browserpass.stat.exists
  - name: Install Ubuntu
    when: browserpass.changed and ansible_facts['os_family'] == 'Ubuntu'
    package:
      name:
        - webext-browserpass
      state: present
    become: true
  - name: Install Archlinux
    when: browserpass.changed and ansible_facts['os_family'] == 'Archlinux'
    package:
      name: browserpass
      state: present
    become: true
  - name: Linking Browserpass host file for Librewolf
    when: browserpass.changed
    make:
      chdir: /usr/lib/browserpass
      target: hosts-librewolf-user
