---
- name: Installing media packages
  package:
    name:
      - vlc
      - minidlna
      - mpv
      - obs-studio
      - audacity
    state: present
  become: true
  tags: always

- name: Creating MiniDLNA config folders
  file:
    path: '/home/{{ user_name }}/.config/minidlna'
    state: directory

- name: Creating MiniDLNA config cache folders
  file:
    path: '/home/{{ user_name }}/.config/minidlna/cache'
    state: directory

- name: Creating MiniDLNA pid file
  file:
    path: '/home/{{ user_name }}/.config/minidlna/minidlna.pid'
    state: touch

- name: Configuring MiniDLNA Server
  template:
    src: '../files/minidlna.conf'
    dest: '/home/{{ user_name }}/.config/minidlna/minidlna.conf'
    force: no
