---
- name: Installing media packages
  pacman:
    name: ['vlc', 'minidlna']
    state: present
  become: true

- name: Creating MiniDLNA config folders
  file:
    path: '/home/{{ user_name }}/.config/minidlna'
    state: directory

- name: Creating MiniDLNA config cache folders
  file:
    path: '/home/{{ user_name }}/.config/minidlna/cache'
    state: directory

- name: Creating MiniDLNA pid file
  file:
    path: '/home/{{ user_name }}/.config/minidlna/minidlna.pid'
    state: file

- name: Configuring MiniDLNA Server
  template:
    src: '../files/minidlna.conf'
    dest: '/home/{{ user_name }}/.config/minidlna/minidlna.conf'
