---
- name: Install docker
  tags: always
  block:
  - name: Installing Docker and docker-compose
    package:
      name:
        - docker
        - docker-compose
      state: present
    become: true

  - name: Active Docker daemon on Systemd
    systemd:
      name: docker
      state: started
      enabled: yes

  - name: 'Adding user to docker group'
    user:
      name: '{{ user_name }}'
      group: docker
      append: yes
    become: true
