---
- include_tasks: asdf.yml
- include_tasks: docker.yml
- include_tasks: zola.yml
- include_tasks: emacs.yml
- include_tasks: ngrok.yml
- include_tasks: elixir.yml

- name: arch development tools
  package:
    name:
      - jq
      - libxml2
      - cmake
      - postgresql-libs
    state: present
  become: true
  when: ansible_facts['os_family'] == 'Archlinux'

- name: arch aur development tools packages
  shell: |
     yay -Qi {{ item }} 2>/dev/null || sudo -u {{ user_name }} yay -S {{ item }} --noconfirm
  with_items:
    - pgformatter-git
  become: true
  when: ansible_facts['os_family'] == 'Archlinux'

- name: ubuntu development tools
  package:
    name:
      - jq
      - libxml2-utils
      - cmake
      - postgresql-client
      - pgformatter
    state: present
  become: true
  when: ansible_facts['os_family'] == 'Ubuntu'
