---
- include: asdf.yml
- include: docker.yml
- include: zola.yml
- include: emacs.yml
- include: ngrok.yml
- include: elixir.yml

- name: Arch Development tools
  package:
    name:
      - jq
      - libxml2
      - cmake
      - postgresql-libs
    state: present
  become: true
  when: ansible_facts['os_family'] == 'Archlinux'

- name: Ubuntu Development tools
  package:
    name:
      - jq
      - libxml2-utils
      - cmake
      - postgresql-client
    state: present
  become: true
  when: ansible_facts['os_family'] == 'Ubuntu'
