---
- include: asdf.yml
- include: docker.yml
- include: zola.yml

- name: Arch Development tools
  package:
    name:
      - jq
      - xmllint
    state: present
  become: true
  tags:
    - arch

- name: Ubuntu Development tools
  package:
    name:
      - jq
      - libxml2-utils
    state: present
  become: true
  tags:
    - ubuntu
