---
- name: Fetching dot-files
  git:
    repo: 'git@github.com:vinikira/dot-files.git'
    dest: '/home/{{ user_name }}/git/github/vinikira/dot-files'
    update: no

- name: Fetching Summon
  git:
    repo: 'https://gitlab.com/semente/summon'
    dest: '/home/{{ user_name }}/git/gitlab/semente/summon'

- name: Given access to summon
  file:
    path: '/home/{{ user_name }}/git/gitlab/semente/summon/summon.sh'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: 0755

- name: Make .local directories
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '/home/{{ user_name }}/.local/bin'
    - '/home/{{ user_name }}/.local/opt'

- name: Create link summon
  file:
    src: '/home/{{ user_name }}/git/gitlab/semente/summon/summon.sh'
    dest: '/home/{{ user_name }}/.local/bin/summon.sh'
    state: link

- name: Summoning dot-files
  shell: 'bash /home/{{ user_name }}/.local/bin/summon.sh /home/{{ user_name }}/git/github/vinikira/dot-files/common/{{ item }}'
  with_items:
    - zsh
    - bin
    - gpg
    - git
    - htop
    - mail
    - tmux
