---
- include: zsh.yml
- include: dot-files.yml
- include: vault.yml
- include: syncthing.yml
- include: tmux.yml

- name: common packages
  package:
    name:
      - aspell
      - aspell-en
      - aspell-pt
      # - ripgrep
      - bat
      - htop
      - pass
      - wget
      - git
      - curl
      - unzip
    state: present
  become: true
  tags: always

- name: arch packages
  package:
    name:
      - ttf-fira-code
      - ttf-jetbrains-mono
      - inotify-tools
      - tmux
      - fd
      - yay
      - paru
      - pandoc-bin
    state: present
  become: true
  tags:
    - arch

- name: ubuntu packages
  package:
    name:
      - fonts-firacode
      - fd-find
      - texlive
      - texlive-latex-extra
      - texlive-publishers
      - pandoc
    state: present
  become: true
  tags:
    - ubuntu
