---
- include: zsh.yml
- include: dot-files.yml

- name: common packages
  package:
    name:
      - aspell
      - aspell-en
      - aspell-pt
      - ripgrep
      - bat
      - tmux
      - htop
      - pass
      - wget
      - git
      - curl
    state: present
  become: true
  tags:
    - ubuntu
    - arch

- name: arch packages
  package:
    name:
      - ttf-fira-code
      - ttf-jetbrains-mono
      - inotify-tools
      - fd
      - yay
      - paru
    state: present
  become: true
  tags:
    - arch

- name: ubuntu packages
  package:
    name:
      - fonts-firacode
      - fd-find
    state: present
  become: true
  tags:
    - ubuntu
