---
- include_tasks: zsh.yml
- include_tasks: dot-files.yml
- include_tasks: vault.yml
- include_tasks: syncthing.yml
- include_tasks: tmux.yml

- name: common packages
  package:
    name:
      - aspell
      - aspell-en
      - aspell-pt
      - ripgrep
      - bat
      - htop
      - pass
      - wget
      - git
      - curl
      - unzip
      - rclone
    state: present
  become: true

- name: arch packages
  package:
    name:
      - inotify-tools
      - tmux
      - fd
      - yay
      - restic
    state: present
  become: true
  when: ansible_facts['os_family'] == 'Archlinux'

- name: arch AUR packages
  shell: |
     yay -Qi {{ item }} 2>/dev/null || sudo -u {{ user_name }} yay -S {{ item }} --noconfirm
  with_items:
    - paru-bin
    - pandoc-bin
  become: true
  when: ansible_facts['os_family'] == 'Archlinux'

- name: ubuntu packages
  package:
    name:
      - fd-find
      - texlive
      - texlive-latex-extra
      - texlive-publishers
      - pandoc
    state: present
  become: true
  when: ansible_facts['os_family'] == 'Ubuntu'
