---
- name: Installing Syncthing
  package:
    name:
      - syncthing
    state: present
  become: true

- name: Start and enable Syncthing service
  systemd:
    name: syncthing
    state: started
    enabled: yes
    scope: user

- name: Allow port used by Syncthing
  ufw:
    rule: allow
    port: 22000
    proto: tcp
  become: true
